server:
  port: 8080

spring:
  application:
    name: chat
  ai:
    # api和key分享自：https://pgthinker.me/2023/10/03/196/
    openai:
      api-key: sk-W0KF2fh5BTX3fEUvBf1262B948354c03B079C94956CfD4B5
      base-url: https://api.mnzdna.xyz
      chat:
        options:
          temperature: 0.7
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration


  datasource:
    username: postgres
    password: zxy13319736887
    url: jdbc:postgresql://localhost:5432/vector_store
